#travis ci file for Project-Lava

language: c
#compiler: gcc -std=c99
dist: trusty
sudo: true


script:
        - cd Alex/FrameworkTest 
          #        - clang -pthread queuecode.c
          #        - ./a.out 2 1
        - make
          #n = 1
        - ./framework 1 1
        - ./framework 1 2
        - ./framework 1 3
        - ./framework 1 4
        - ./framework 1 5
        - ./framework 1 6
        - ./framework 1 7
        - ./framework 1 8
          #n = 2
        - ./framework 2 1
        - ./framework 2 2
        - ./framework 2 3
        - ./framework 2 4
        - ./framework 2 5
        - ./framework 2 6
        - ./framework 2 7
        - ./framework 2 8
          #n = 3
        - ./framework 3 1
        - ./framework 3 2
        - ./framework 3 3
        - ./framework 3 4
        - ./framework 3 5
        - ./framework 3 6
        - ./framework 1 7
        - ./framework 1 8
          # n = 4          
        - ./framework 4 1
        - ./framework 4 2
        - ./framework 4 3
        - ./framework 4 4
        - ./framework 4 5
        - ./framework 4 6
        - ./framework 4 7
        - ./framework 4 8
          #n = 5
        - ./framework 5 1
        - ./framework 5 2
        - ./framework 5 3
        - ./framework 5 4
        - ./framework 5 5
        - ./framework 5 6
        - ./framework 5 7
        - ./framework 5 8
         #n = 6
        - ./framework 6 1
        - ./framework 6 2 
        - ./framework 6 3 
        - ./framework 6 4
        - ./framework 6 5
        - ./framework 6 6 
        - ./framework 6 7
        - ./framework 6 8
         #n = 7
        - ./framework 7 1
        - ./framework 7 2
        - ./framework 7 3
        - ./framework 7 4
        - ./framework 7 5
        - ./framework 7 6
        - ./framework 7 7
        - ./framework 7 8
         #n = 8
        - ./framework 8 1
        - ./framework 8 2
        - ./framework 8 3
        - ./framework 8 4
        - ./framework 8 5
        - ./framework 8 6
        - ./framework 8 7
        - ./framework 8 8

#Repeating code adside from the n and m values would be nice if this could be made into a loop.
