#travis ci file for Project-Lava

language: c

compiler:
        - gcc
env:
        - CFLAGS="-std=c99"
sudo: true

script:
        - cd ~/project-lava/NewTestingEnvironment/
        - ./mainScript.sh -q
