#travis ci file for Project-Lava

language: c
#compiler: gcc -std=c99
dist: trusty
sudo: true


script:
        - cd Alex/FrameworkTest 
          #        - clang -pthread queuecode.c
          #        - ./a.out 2 1
        - make
        - ./algorithm 1 1
